// Static mock dataset for the Tennis Roster feature

import type { RosterPlayer } from "../types/roster";
import { District, TennisRanking } from "~/generated/prisma/enums";
import {
  DayOfWeek,
  TimePreference,
  PlayingStyle,
  MatchFormat,
} from "../types/roster";

// Helper function to generate upcoming events
const generateUpcomingEvents = (playerName: string, count: number = 2) => {
  const events = [
    { title: "Volley & Vibes: WEEK 8", location: "Dolores Park Courts" },
    { title: "First Volleys: WEEK 3", location: "Mission Playground Courts" },
    { title: "Flow: WEEK 5", location: "Hamilton Tennis Courts" },
    { title: "Vibras y Voleas: WEEK 2", location: "Joe DiMaggio Courts" },
    { title: "Social Rally: WEEK 4", location: "Glen Park Courts" },
    { title: "Doubles Clinic: WEEK 6", location: "Lafayette Tennis Court" },
  ];

  const selectedEvents = [];
  const now = new Date();

  for (let i = 0; i < count; i++) {
    const daysAhead = Math.floor(Math.random() * 14) + 1;
    const eventDate = new Date(now.getTime() + daysAhead * 24 * 60 * 60 * 1000);
    const event = events[Math.floor(Math.random() * events.length)];

    selectedEvents.push({
      id: `event-${playerName}-${i}`,
      title: event.title,
      date: eventDate,
      location: event.location,
    });
  }

  return selectedEvents;
};

// Static mock player dataset
export const mockPlayers: RosterPlayer[] = [
  // Complete profiles (25 players)
  {
    id: "player-1",
    firstName: "Alex",
    lastName: "Chen",
    district: District.District7,
    tennisRanking: TennisRanking.FOUR_ZERO,
    instagramHandle: "@alexserves",
    favoriteTennisPlayer: "Roger Federer",
    playlistSong: "Eye of the Tiger - Survivor",
    availability: [
      { day: DayOfWeek.Tuesday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Thursday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Saturday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Sets, PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Singles, MatchFormat.Doubles],
    tennisRoles: [
      {
        id: "role-1",
        name: "Event Host",
        description: "Organizes weekly tennis events",
      },
      {
        id: "role-2",
        name: "Coach",
        description: "Certified tennis instructor",
      },
    ],
    upcomingEvents: generateUpcomingEvents("alex", 3),
    isProfileComplete: true,
  },
  {
    id: "player-2",
    firstName: "Maria",
    lastName: "Rodriguez",
    district: District.District9,
    tennisRanking: TennisRanking.THREE_FIVE,
    instagramHandle: "@maria_ace",
    favoriteTennisPlayer: "Serena Williams",
    playlistSong: "Levitating - Dua Lipa",
    availability: [
      { day: DayOfWeek.Monday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Wednesday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Sunday, timePreference: TimePreference.AllDay },
    ],
    playingStyles: [PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Doubles, MatchFormat.Mixed],
    tennisRoles: [
      { id: "role-3", name: "Player", description: "Active community member" },
    ],
    upcomingEvents: generateUpcomingEvents("maria", 2),
    isProfileComplete: true,
  },
  {
    id: "player-3",
    firstName: "James",
    lastName: "Kim",
    district: District.District3,
    tennisRanking: TennisRanking.FOUR_FIVE,
    instagramHandle: "@jkim_tennis",
    favoriteTennisPlayer: "Novak Djokovic",
    playlistSong: "Can't Stop the Feeling - Justin Timberlake",
    availability: [
      { day: DayOfWeek.Wednesday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Friday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Saturday, timePreference: TimePreference.AllDay },
    ],
    playingStyles: [PlayingStyle.Sets, PlayingStyle.ServePractice],
    matchFormats: [MatchFormat.Singles],
    tennisRoles: [
      {
        id: "role-4",
        name: "Tournament Director",
        description: "Organizes competitive events",
      },
    ],
    upcomingEvents: generateUpcomingEvents("james", 1),
    isProfileComplete: true,
  },
  {
    id: "player-4",
    firstName: "Sarah",
    lastName: "Johnson",
    district: District.District1,
    tennisRanking: TennisRanking.THREE_ZERO,
    instagramHandle: "@sarahvolleygirl",
    favoriteTennisPlayer: "Naomi Osaka",
    playlistSong: "Flowers - Miley Cyrus",
    availability: [
      { day: DayOfWeek.Tuesday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Thursday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Rallies, PlayingStyle.ServePractice],
    matchFormats: [MatchFormat.Doubles],
    tennisRoles: [
      { id: "role-5", name: "Player", description: "Active community member" },
    ],
    upcomingEvents: generateUpcomingEvents("sarah", 2),
    isProfileComplete: true,
  },
  {
    id: "player-5",
    firstName: "Michael",
    lastName: "Thompson",
    district: District.District6,
    tennisRanking: TennisRanking.FIVE_ZERO,
    instagramHandle: "@mthompson_sf",
    favoriteTennisPlayer: "Andy Murray",
    playlistSong: "Thunder - Imagine Dragons",
    availability: [
      { day: DayOfWeek.Monday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Saturday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Sunday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Sets],
    matchFormats: [MatchFormat.Singles, MatchFormat.Doubles],
    tennisRoles: [
      {
        id: "role-6",
        name: "Coach",
        description: "Certified tennis instructor",
      },
    ],
    upcomingEvents: generateUpcomingEvents("michael", 3),
    isProfileComplete: true,
  },
  {
    id: "player-6",
    firstName: "Emily",
    lastName: "Zhang",
    district: District.District4,
    tennisRanking: TennisRanking.THREE_FIVE,
    instagramHandle: "@em_zhang",
    favoriteTennisPlayer: "Coco Gauff",
    playlistSong: "Good 4 U - Olivia Rodrigo",
    availability: [
      { day: DayOfWeek.Wednesday, timePreference: TimePreference.AllDay },
      { day: DayOfWeek.Friday, timePreference: TimePreference.Evening },
    ],
    playingStyles: [PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Mixed],
    tennisRoles: [
      {
        id: "role-7",
        name: "Event Host",
        description: "Organizes weekly tennis events",
      },
    ],
    upcomingEvents: generateUpcomingEvents("emily", 2),
    isProfileComplete: true,
  },
  {
    id: "player-7",
    firstName: "David",
    lastName: "Martinez",
    district: District.District10,
    tennisRanking: TennisRanking.FOUR_ZERO,
    instagramHandle: "@dmartinez_tennis",
    favoriteTennisPlayer: "Rafael Nadal",
    playlistSong: "Viva La Vida - Coldplay",
    availability: [
      { day: DayOfWeek.Tuesday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Thursday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Sunday, timePreference: TimePreference.AllDay },
    ],
    playingStyles: [PlayingStyle.Sets, PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Singles],
    tennisRoles: [
      { id: "role-8", name: "Player", description: "Active community member" },
    ],
    upcomingEvents: generateUpcomingEvents("david", 1),
    isProfileComplete: true,
  },
  {
    id: "player-8",
    firstName: "Lisa",
    lastName: "Wang",
    district: District.District2,
    tennisRanking: TennisRanking.TWO_FIVE,
    instagramHandle: "@lisawang_sf",
    favoriteTennisPlayer: "Li Na",
    playlistSong: "Shake It Off - Taylor Swift",
    availability: [
      { day: DayOfWeek.Monday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Friday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Doubles, MatchFormat.Mixed],
    tennisRoles: [
      {
        id: "role-9",
        name: "Social Coordinator",
        description: "Organizes social events",
      },
    ],
    upcomingEvents: generateUpcomingEvents("lisa", 2),
    isProfileComplete: true,
  },
  {
    id: "player-9",
    firstName: "Robert",
    lastName: "Davis",
    district: District.District8,
    tennisRanking: TennisRanking.FOUR_FIVE,
    instagramHandle: "@rdavis_tennis",
    favoriteTennisPlayer: "Pete Sampras",
    playlistSong: "Mr. Brightside - The Killers",
    availability: [
      { day: DayOfWeek.Wednesday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Saturday, timePreference: TimePreference.AllDay },
    ],
    playingStyles: [PlayingStyle.Sets, PlayingStyle.ServePractice],
    matchFormats: [MatchFormat.Singles, MatchFormat.Doubles],
    tennisRoles: [
      { id: "role-10", name: "Player", description: "Active community member" },
    ],
    upcomingEvents: generateUpcomingEvents("robert", 1),
    isProfileComplete: true,
  },
  {
    id: "player-10",
    firstName: "Amanda",
    lastName: "Lee",
    district: District.District5,
    tennisRanking: TennisRanking.THREE_ZERO,
    instagramHandle: "@amanda_serves",
    favoriteTennisPlayer: "Simona Halep",
    playlistSong: "Blinding Lights - The Weeknd",
    availability: [
      { day: DayOfWeek.Monday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Tuesday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Thursday, timePreference: TimePreference.Evening },
    ],
    playingStyles: [PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Doubles],
    tennisRoles: [
      { id: "role-11", name: "Player", description: "Active community member" },
    ],
    upcomingEvents: generateUpcomingEvents("amanda", 3),
    isProfileComplete: true,
  },
  {
    id: "player-11",
    firstName: "Kevin",
    lastName: "Patel",
    district: District.District11,
    tennisRanking: TennisRanking.FIVE_FIVE,
    instagramHandle: "@kpatel_tennis",
    favoriteTennisPlayer: "Andre Agassi",
    playlistSong: "Pump It - The Black Eyed Peas",
    availability: [
      { day: DayOfWeek.Saturday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Sunday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Sets],
    matchFormats: [MatchFormat.Singles],
    tennisRoles: [
      {
        id: "role-12",
        name: "Beginner Coordinator",
        description: "Helps new players",
      },
    ],
    upcomingEvents: generateUpcomingEvents("kevin", 2),
    isProfileComplete: true,
  },
  {
    id: "player-12",
    firstName: "Rachel",
    lastName: "Green",
    district: District.District7,
    tennisRanking: TennisRanking.FOUR_ZERO,
    instagramHandle: "@rachelgreen_sf",
    favoriteTennisPlayer: "Steffi Graf",
    playlistSong: "Dancing Queen - ABBA",
    availability: [
      { day: DayOfWeek.Wednesday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Friday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Sunday, timePreference: TimePreference.AllDay },
    ],
    playingStyles: [PlayingStyle.Rallies, PlayingStyle.ServePractice],
    matchFormats: [MatchFormat.Mixed],
    tennisRoles: [
      {
        id: "role-13",
        name: "Event Host",
        description: "Organizes weekly tennis events",
      },
    ],
    upcomingEvents: generateUpcomingEvents("rachel", 2),
    isProfileComplete: true,
  },
  {
    id: "player-13",
    firstName: "Daniel",
    lastName: "Wilson",
    district: District.District3,
    tennisRanking: TennisRanking.THREE_FIVE,
    instagramHandle: "@dwilson_tennis",
    favoriteTennisPlayer: "Juan Martin del Potro",
    playlistSong: "Radioactive - Imagine Dragons",
    availability: [
      { day: DayOfWeek.Tuesday, timePreference: TimePreference.AllDay },
      { day: DayOfWeek.Thursday, timePreference: TimePreference.Evening },
    ],
    playingStyles: [PlayingStyle.Sets],
    matchFormats: [MatchFormat.Singles, MatchFormat.Doubles],
    tennisRoles: [
      { id: "role-14", name: "Player", description: "Active community member" },
    ],
    upcomingEvents: generateUpcomingEvents("daniel", 1),
    isProfileComplete: true,
  },
  {
    id: "player-14",
    firstName: "Sophie",
    lastName: "Anderson",
    district: District.District1,
    tennisRanking: TennisRanking.TWO_ZERO,
    instagramHandle: "@sophietennis",
    favoriteTennisPlayer: "Venus Williams",
    playlistSong: "Happy - Pharrell Williams",
    availability: [
      { day: DayOfWeek.Monday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Wednesday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Friday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Doubles],
    tennisRoles: [
      {
        id: "role-15",
        name: "Coach",
        description: "Certified tennis instructor",
      },
    ],
    upcomingEvents: generateUpcomingEvents("sophie", 2),
    isProfileComplete: true,
  },
  {
    id: "player-15",
    firstName: "Chris",
    lastName: "Taylor",
    district: District.District6,
    tennisRanking: TennisRanking.FOUR_FIVE,
    instagramHandle: "@ctaylor_sf",
    favoriteTennisPlayer: "John McEnroe",
    playlistSong: "Sweet Caroline - Neil Diamond",
    availability: [
      { day: DayOfWeek.Thursday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Saturday, timePreference: TimePreference.AllDay },
    ],
    playingStyles: [PlayingStyle.Sets, PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Singles],
    tennisRoles: [
      { id: "role-16", name: "Player", description: "Active community member" },
    ],
    upcomingEvents: generateUpcomingEvents("chris", 1),
    isProfileComplete: true,
  },
  {
    id: "player-16",
    firstName: "Nicole",
    lastName: "Brown",
    district: District.District9,
    tennisRanking: TennisRanking.THREE_ZERO,
    instagramHandle: "@nicolebrown_tennis",
    favoriteTennisPlayer: "Maria Sharapova",
    playlistSong: "Roar - Katy Perry",
    availability: [
      { day: DayOfWeek.Tuesday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Sunday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Rallies, PlayingStyle.ServePractice],
    matchFormats: [MatchFormat.Doubles, MatchFormat.Mixed],
    tennisRoles: [
      {
        id: "role-17",
        name: "Tournament Director",
        description: "Organizes competitive events",
      },
    ],
    upcomingEvents: generateUpcomingEvents("nicole", 3),
    isProfileComplete: true,
  },
  {
    id: "player-17",
    firstName: "Ryan",
    lastName: "Garcia",
    district: District.District4,
    tennisRanking: TennisRanking.FIVE_ZERO,
    instagramHandle: "@rgarcia_tennis",
    favoriteTennisPlayer: "Carlos Alcaraz",
    playlistSong: "Uptown Funk - Bruno Mars",
    availability: [
      { day: DayOfWeek.Monday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Wednesday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Friday, timePreference: TimePreference.Evening },
    ],
    playingStyles: [PlayingStyle.Sets],
    matchFormats: [MatchFormat.Singles],
    tennisRoles: [
      { id: "role-18", name: "Player", description: "Active community member" },
    ],
    upcomingEvents: generateUpcomingEvents("ryan", 2),
    isProfileComplete: true,
  },
  {
    id: "player-18",
    firstName: "Jessica",
    lastName: "Moore",
    district: District.District2,
    tennisRanking: TennisRanking.THREE_FIVE,
    instagramHandle: "@jmoore_sf",
    favoriteTennisPlayer: "Ashleigh Barty",
    playlistSong: "Stronger - Kelly Clarkson",
    availability: [
      { day: DayOfWeek.Tuesday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Saturday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Doubles],
    tennisRoles: [
      {
        id: "role-19",
        name: "Social Coordinator",
        description: "Organizes social events",
      },
    ],
    upcomingEvents: generateUpcomingEvents("jessica", 1),
    isProfileComplete: true,
  },
  {
    id: "player-19",
    firstName: "Brandon",
    lastName: "Hall",
    district: District.District8,
    tennisRanking: TennisRanking.FOUR_ZERO,
    instagramHandle: "@bhall_tennis",
    favoriteTennisPlayer: "Stan Wawrinka",
    playlistSong: "Seven Nation Army - The White Stripes",
    availability: [
      { day: DayOfWeek.Wednesday, timePreference: TimePreference.AllDay },
      { day: DayOfWeek.Sunday, timePreference: TimePreference.AllDay },
    ],
    playingStyles: [PlayingStyle.Sets, PlayingStyle.ServePractice],
    matchFormats: [MatchFormat.Singles, MatchFormat.Doubles],
    tennisRoles: [
      { id: "role-20", name: "Player", description: "Active community member" },
    ],
    upcomingEvents: generateUpcomingEvents("brandon", 2),
    isProfileComplete: true,
  },
  {
    id: "player-20",
    firstName: "Michelle",
    lastName: "Lopez",
    district: District.District5,
    tennisRanking: TennisRanking.TWO_FIVE,
    instagramHandle: "@mlopez_tennis",
    favoriteTennisPlayer: "Iga Swiatek",
    playlistSong: "Shut Up and Dance - WALK THE MOON",
    availability: [
      { day: DayOfWeek.Monday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Thursday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Mixed],
    tennisRoles: [
      {
        id: "role-21",
        name: "Event Host",
        description: "Organizes weekly tennis events",
      },
    ],
    upcomingEvents: generateUpcomingEvents("michelle", 3),
    isProfileComplete: true,
  },
  {
    id: "player-21",
    firstName: "Steven",
    lastName: "Nguyen",
    district: District.District10,
    tennisRanking: TennisRanking.FOUR_FIVE,
    instagramHandle: "@snguyen_sf",
    favoriteTennisPlayer: "Kei Nishikori",
    playlistSong: "Believer - Imagine Dragons",
    availability: [
      { day: DayOfWeek.Friday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Saturday, timePreference: TimePreference.AllDay },
    ],
    playingStyles: [PlayingStyle.Sets, PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Singles],
    tennisRoles: [
      { id: "role-22", name: "Player", description: "Active community member" },
    ],
    upcomingEvents: generateUpcomingEvents("steven", 1),
    isProfileComplete: true,
  },
  {
    id: "player-22",
    firstName: "Lauren",
    lastName: "White",
    district: District.District7,
    tennisRanking: TennisRanking.THREE_ZERO,
    instagramHandle: "@lwhite_tennis",
    favoriteTennisPlayer: "Emma Raducanu",
    playlistSong: "High Hopes - Panic! At The Disco",
    availability: [
      { day: DayOfWeek.Tuesday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Thursday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Sunday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Rallies, PlayingStyle.ServePractice],
    matchFormats: [MatchFormat.Doubles],
    tennisRoles: [
      {
        id: "role-23",
        name: "Beginner Coordinator",
        description: "Helps new players",
      },
    ],
    upcomingEvents: generateUpcomingEvents("lauren", 2),
    isProfileComplete: true,
  },
  {
    id: "player-23",
    firstName: "Jason",
    lastName: "Clark",
    district: District.District3,
    tennisRanking: TennisRanking.FIVE_FIVE,
    instagramHandle: "@jclark_sf",
    favoriteTennisPlayer: "Dominic Thiem",
    playlistSong: "Can't Hold Us - Macklemore",
    availability: [
      { day: DayOfWeek.Wednesday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Friday, timePreference: TimePreference.Evening },
    ],
    playingStyles: [PlayingStyle.Sets],
    matchFormats: [MatchFormat.Singles, MatchFormat.Doubles],
    tennisRoles: [
      { id: "role-24", name: "Player", description: "Active community member" },
    ],
    upcomingEvents: generateUpcomingEvents("jason", 1),
    isProfileComplete: true,
  },
  {
    id: "player-24",
    firstName: "Olivia",
    lastName: "Robinson",
    district: District.District1,
    tennisRanking: TennisRanking.THREE_FIVE,
    instagramHandle: "@orobinson_tennis",
    favoriteTennisPlayer: "Billie Jean King",
    playlistSong: "Don't Stop Me Now - Queen",
    availability: [
      { day: DayOfWeek.Monday, timePreference: TimePreference.AllDay },
      { day: DayOfWeek.Saturday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Mixed],
    tennisRoles: [
      {
        id: "role-25",
        name: "Coach",
        description: "Certified tennis instructor",
      },
      {
        id: "role-26",
        name: "Event Host",
        description: "Organizes weekly tennis events",
      },
    ],
    upcomingEvents: generateUpcomingEvents("olivia", 3),
    isProfileComplete: true,
  },
  {
    id: "player-25",
    firstName: "Matthew",
    lastName: "Adams",
    district: District.District6,
    tennisRanking: TennisRanking.FOUR_ZERO,
    instagramHandle: "@madams_tennis",
    favoriteTennisPlayer: "Andy Roddick",
    playlistSong: "Thunderstruck - AC/DC",
    availability: [
      { day: DayOfWeek.Tuesday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Thursday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Saturday, timePreference: TimePreference.AllDay },
    ],
    playingStyles: [PlayingStyle.Sets, PlayingStyle.ServePractice],
    matchFormats: [MatchFormat.Singles],
    tennisRoles: [
      {
        id: "role-27",
        name: "Tournament Director",
        description: "Organizes competitive events",
      },
    ],
    upcomingEvents: generateUpcomingEvents("matthew", 2),
    isProfileComplete: true,
  },

  // Incomplete profiles (5 players)
  {
    id: "player-26",
    firstName: "Thomas",
    lastName: "Baker",
    district: District.District9,
    tennisRanking: TennisRanking.THREE_ZERO,
    // Missing social handles and personality info
    availability: [
      { day: DayOfWeek.Monday, timePreference: TimePreference.Evening },
    ],
    playingStyles: [PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Doubles],
    tennisRoles: [
      { id: "role-28", name: "Player", description: "Active community member" },
    ],
    isProfileComplete: false,
  },
  {
    id: "player-27",
    firstName: "Emma",
    lastName: "Turner",
    district: District.District4,
    tennisRanking: TennisRanking.TWO_FIVE,
    instagramHandle: "@emma_t",
    // Missing favorite player and playlist song
    availability: [
      { day: DayOfWeek.Wednesday, timePreference: TimePreference.Morning },
      { day: DayOfWeek.Friday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Mixed],
    tennisRoles: [
      { id: "role-29", name: "Player", description: "Active community member" },
    ],
    isProfileComplete: false,
  },
  {
    id: "player-28",
    firstName: "Andrew",
    lastName: "Phillips",
    district: District.District2,
    tennisRanking: TennisRanking.FOUR_FIVE,
    // Very minimal profile
    availability: [],
    playingStyles: [],
    matchFormats: [],
    tennisRoles: [
      { id: "role-30", name: "Player", description: "Active community member" },
    ],
    isProfileComplete: false,
  },
  {
    id: "player-29",
    firstName: "Grace",
    lastName: "Mitchell",
    district: District.District8,
    tennisRanking: TennisRanking.THREE_FIVE,
    favoriteTennisPlayer: "Caroline Wozniacki",
    // Missing Instagram and playlist song
    availability: [
      { day: DayOfWeek.Saturday, timePreference: TimePreference.Morning },
    ],
    playingStyles: [PlayingStyle.Sets],
    matchFormats: [MatchFormat.Singles],
    tennisRoles: [
      { id: "role-31", name: "Player", description: "Active community member" },
    ],
    isProfileComplete: false,
  },
  {
    id: "player-30",
    firstName: "Peter",
    lastName: "Evans",
    district: District.District5,
    tennisRanking: TennisRanking.FIVE_ZERO,
    instagramHandle: "@pevans",
    playlistSong: "We Will Rock You - Queen",
    // Missing favorite player
    availability: [
      { day: DayOfWeek.Tuesday, timePreference: TimePreference.Evening },
      { day: DayOfWeek.Thursday, timePreference: TimePreference.Evening },
    ],
    playingStyles: [PlayingStyle.Sets, PlayingStyle.Rallies],
    matchFormats: [MatchFormat.Singles, MatchFormat.Doubles],
    tennisRoles: [
      {
        id: "role-32",
        name: "Social Coordinator",
        description: "Organizes social events",
      },
    ],
    upcomingEvents: generateUpcomingEvents("peter", 1),
    isProfileComplete: false,
  },
];
